### ISSUE TITLE
Where are you at with this?

### ISSUE THREAD

**Issue by justinmchase** [maierfelix/mini-c#7]
I've been doing a lot of searching lately and I keep coming back to this repo. It seems you and I think a like in some ways and I get why you're working on this. I've been trying to find out if there is something that will do what I want but it seems like not.

And what I want is to make a higher level language that targets wasm without using the traditional toolset. I don't mind writing parts of the runtime in a lower  level language but I don't want to have to do it with  a bunch of giant, slow, heavy weight to install tools which can only be invoked from the command line. I want the compilation features to be apart of the language itself, dynamic so to speak.

But here I am writing raw wat files, which is fine, but now I'm to the point where I need malloc/free essentially. I did try importing a wasm file someone else made which just compiles the C stdlib but it doesn't work right and I'm not sure why. Its continually returning pointers for outside the bounds of memory.

What I'm thinking is that what I may do is try to implement this:
https://www.math.uni-bielefeld.de/~rehmann/Ckurs-f/b04/alloc.h

But doing that in wat manually could be a little tricky. There's a few things that C takes care of such as structs and unions and pointers, which wat doesn't do natively. So basically when I look at what you have here I feel like its pretty close. All you'd need would be structs and unions I think.

One thing I would do with this, maybe you already have, would be to not try to support all of C but to instead pick just the primitives directly supported by wasm. Plus the little bit needed to add a layer of abstraction, such as structs and pointers. And then add a standard library which includes malloc/free etc.

This would be extremely useful for anyone building a _new_ language ontop of wasm. The bigger tools compiling full C will be useful for people with existing projects, compiling libraries into something that can be used in wasm. But I feel like its not really desirable from scratch to use those tools for a variety of reasons.

**Comment by maierfelix** [comment]
Hi, thanks for checking out!

This was a 2 week holiday project to learn C and Wasm, I left because C was horrible to parse and Wasm's specification was filled with unicorns at that time. The project didn't have any goal for me than getting a sense of Wasm for future projects.

I'm currently active in a very different topic than compilers, but as soon as I'm finished there I will probably come back. This project however won't get developed further and just sits here as hopefully a useful resource (like the *emit* file) - actually *walt* is based on this project, but I'd rather use Wasm directly to have everything I need without having to create workarounds or learn a library's flow.

Wasm's format is very straightforward and I think there is no need to create abstraction on top of it.

I'd like to recommend you [this](https://github.com/dcodeIO/webassembly) toolkit, it's minimal and a great way to create hybrid JS-Wasm apps (I'm using it [here](https://github.com/maierfelix/glmw)).

**Comment by justinmchase** [comment]
Oh cool, it looks like `walt` is very close to what I was imagining, I'll look at that more closely. As I'm messing more with wasm I'm finding it pretty easy also. I actually find pointers easier to think about as just load operations rather than local references, strangely. But perhaps walt will still be beneficial. I may have to try it.

The toolkit you linked looks interesting too but I don't want a cli tool with binaries and such. Thanks for the words.
